changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
  categories:
    - title: "Features"
      labels:
        - feat
        - feature
    - title: "Fixes"
      labels:
        - fix
        - bug
    - title: "Tests"
      labels:
        - test
        - tests
    - title: "Maintenance"
      labels:
        - chore
        - docs
        - refactor
        - ci
